### ISSUE TITLE
E 0:00:02:0152   emit_signalp: Caller thread can't call this function in this node (/root/YtDlp). Use call_deferred() or call_thread_group() instead.   <C++ Error>    Condition "!is_accessible_from_caller_thread()" is true. Returning: (ERR_INVALID_PARAMETER)   <C++ Source>   scene/main/node.cpp:3570 @ emit_signalp()

### ISSUE THREAD

**Issue by nopxjs** [Nolkaloid/godot-yt-dlp#9]
my script 
`
extends Node3D

func _ready():
	if not YtDlp.is_setup():
		YtDlp.setup()
		await YtDlp.setup_completed
	var download := YtDlp.download("https://youtube.com/watch?v=dQw4w9WgXcQ") \
			.set_destination("user://audio/") \
			.set_file_name("ok_computer") \
			.convert_to_audio(YtDlp.Audio.MP3) \
			.start()

	await download.download_completed

	var stream = AudioStreamMP3.new()
	var audio_file = FileAccess.open("user://audio/ok_computer.mp3", FileAccess.READ)

	stream.data = audio_file.get_buffer(audio_file.get_length())
	audio_file.close()

	$AudioStreamPlayer.stream = stream
	$AudioStreamPlayer.play()
`

**Comment by nopxjs** [comment]
i use godot 4.1.1

**Comment by Nolkaloid** [comment]
Fixed ! Thanks for reporting @nopxjs :)
